WEBHOOK_SOURCE_EMAIL = "email"
WEBHOOK_SOURCE_TELEGRAM = "telegram"

WEBHOOK_ACTION_EMAIL_INBOUND = "email.inbound"
WEBHOOK_ACTION_TELEGRAM_MESSAGE = "telegram.message"

HEADER_SIGNATURE = "X-Webhook-Signature"
HEADER_TIMESTAMP = "X-Webhook-Timestamp"
HEADER_IDEMPOTENCY = "X-Idempotency-Key"
HEADER_TENANT_ID = "X-Tenant-Id"

MAX_PAYLOAD_SIZE = 1_048_576

MAX_TIMESTAMP_AGE_SECONDS = 300

SIGNATURE_PREFIX = "sha256="

WEBHOOK_AUDIT_ACTION_RECEIVED = "WEBHOOK_RECEIVED"
WEBHOOK_AUDIT_ACTION_REJECTED = "WEBHOOK_REJECTED"
WEBHOOK_AUDIT_ACTION_PROCESSED = "WEBHOOK_PROCESSED"
