NOTIFICATION_TYPE_INFO = "info"
NOTIFICATION_TYPE_WARNING = "warning"
NOTIFICATION_TYPE_SUCCESS = "success"
NOTIFICATION_TYPE_ERROR = "error"

TRANSPORT_WEBSOCKET = "websocket"
TRANSPORT_TELEGRAM = "telegram"
TRANSPORT_EMAIL = "email"

DEFAULT_TRANSPORTS = [TRANSPORT_WEBSOCKET]
