# Event source domains
SOURCE_AUTH = "auth"
SOURCE_TICKETS = "tickets"
SOURCE_WEBHOOKS = "webhooks"
SOURCE_NOTIFICATIONS = "notifications"
SOURCE_TENANT = "tenant"
SOURCE_SYSTEM = "system"

# Auth events
ACTION_AUTH_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
ACTION_AUTH_LOGIN_FAILED = "USER_LOGIN_FAILED"
ACTION_AUTH_REGISTER = "USER_REGISTERED"
ACTION_AUTH_ROLE_CHANGE = "USER_ROLE_CHANGED"
ACTION_AUTH_PASSWORD_CHANGE = "USER_PASSWORD_CHANGED"

# Ticket lifecycle events
ACTION_TICKET_CREATED = "TICKET_CREATED"
ACTION_TICKET_UPDATED = "TICKET_UPDATED"
ACTION_TICKET_ASSIGNED = "TICKET_ASSIGNED"
ACTION_TICKET_RESOLVED = "TICKET_RESOLVED"
ACTION_TICKET_CLOSED = "TICKET_CLOSED"
ACTION_TICKET_REOPENED = "TICKET_REOPENED"
ACTION_TICKET_DELETED = "TICKET_DELETED"
ACTION_TICKET_RATED = "TICKET_RATED"

# Comment events
ACTION_COMMENT_CREATED = "COMMENT_CREATED"

# Webhook events
ACTION_WEBHOOK_RECEIVED = "WEBHOOK_RECEIVED"
ACTION_WEBHOOK_PROCESSED = "WEBHOOK_PROCESSED"
ACTION_WEBHOOK_REJECTED = "WEBHOOK_REJECTED"

# Notification events
ACTION_NOTIFICATION_DISPATCHED = "NOTIFICATION_DISPATCHED"
ACTION_NOTIFICATION_READ = "NOTIFICATION_READ"

# SLA events
ACTION_SLA_BREACH = "SLA_BREACH"
ACTION_SLA_WARNING = "SLA_WARNING"
ACTION_SLA_RESET = "SLA_RESET"

# Tenant events
ACTION_TENANT_CREATED = "TENANT_CREATED"
ACTION_TENANT_SETTINGS_CHANGE = "TENANT_SETTINGS_CHANGE"

# Permission events
ACTION_PERMISSION_DENIED = "PERMISSION_DENIED"
