"""Add Multi-tenancy and Timeline

Revision ID: 0c7241e355ea
Revises: f3617e7ae11e
Create Date: 2026-02-02 18:34:27.231489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as unused_postgresql  # kept for reference

# revision identifiers, used by Alembic.
revision: str = '0c7241e355ea'
down_revision: Union[str, None] = 'f3617e7ae11e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('ticket_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_statuses_id'), 'ticket_statuses', ['id'], unique=False)
    op.create_table('ticket_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_timeline_id'), 'ticket_timeline', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_timeline_ticket_id'), 'ticket_timeline', ['ticket_id'], unique=False)
    op.drop_index('ix_comments_id', table_name='comments')
    op.drop_index('ix_comments_ticket_id', table_name='comments')
    op.drop_table('comments')
    op.add_column('tickets', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.add_column('tickets', sa.Column('readable_id', sa.Integer(), nullable=False))
    op.add_column('tickets', sa.Column('status_id', sa.Integer(), nullable=False))
    op.add_column('tickets', sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('tickets', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticketpriority'),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('ix_tickets_priority', table_name='tickets')
    op.drop_index('ix_tickets_status', table_name='tickets')
    op.create_index(op.f('ix_tickets_tenant_id'), 'tickets', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'tickets', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'ticket_statuses', ['status_id'], ['id'])
    op.drop_column('tickets', 'status')
    op.add_column('users', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'role')
    op.drop_column('users', 'tenant_id')
    op.add_column('tickets', sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_tenant_id'), table_name='tickets')
    op.create_index('ix_tickets_status', 'tickets', ['status'], unique=False)
    op.create_index('ix_tickets_priority', 'tickets', ['priority'], unique=False)
    op.alter_column('tickets', 'priority',
               existing_type=sa.String(),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticketpriority'),
               existing_nullable=False)
    op.drop_column('tickets', 'sla_due_at')
    op.drop_column('tickets', 'status_id')
    op.drop_column('tickets', 'readable_id')
    op.drop_column('tickets', 'tenant_id')
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name='comments_ticket_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='comments_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='comments_pkey')
    )
    op.create_index('ix_comments_ticket_id', 'comments', ['ticket_id'], unique=False)
    op.create_index('ix_comments_id', 'comments', ['id'], unique=False)
    op.drop_index(op.f('ix_ticket_timeline_ticket_id'), table_name='ticket_timeline')
    op.drop_index(op.f('ix_ticket_timeline_id'), table_name='ticket_timeline')
    op.drop_table('ticket_timeline')
    op.drop_index(op.f('ix_ticket_statuses_id'), table_name='ticket_statuses')
    op.drop_table('ticket_statuses')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
