from fastapi import FastAPI, Request, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from app.routers import auth, tickets, comments, notifications, webhooks, analytics, users, crm, timetracking, knowledgebase, audit, features, reports
from app.config import settings
from app.logger import log_request, setup_logging
from app.services.websocket_manager import manager
from app.database import engine, Base
from jose import jwt
import time
import asyncio
from contextlib import asynccontextmanager

# Initialize logging
setup_logging()

@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup: Create tables if not exist
    try:
        Base.metadata.create_all(bind=engine)
        print("Database tables initialized.")
        
        # Add missing columns for existing databases
        from sqlalchemy import inspect, text
        with engine.connect() as conn:
            insp = inspect(engine)
            
            if 'companies' in insp.get_table_names():
                existing_cols = [c['name'] for c in insp.get_columns('companies')]
                new_cols = {
                    'legal_name': 'VARCHAR',
                    'inn': 'VARCHAR',
                    'address': 'VARCHAR',
                    'phone': 'VARCHAR',
                    'email': 'VARCHAR',
                    'website': 'VARCHAR',
                    'logo_url': 'VARCHAR',
                    'description': 'TEXT',
                }
                for col_name, col_type in new_cols.items():
                    if col_name not in existing_cols:
                        conn.execute(text(f'ALTER TABLE companies ADD COLUMN {col_name} {col_type}'))
                        print(f"Added '{col_name}' column to companies")
                conn.commit()
            
            if 'tickets' in insp.get_table_names():
                ticket_cols = [c['name'] for c in insp.get_columns('tickets')]
                ticket_new = {
                    'scheduled_at': 'TIMESTAMP WITH TIME ZONE',
                    'accepted_at': 'TIMESTAMP WITH TIME ZONE',
                    'closed_by': 'INTEGER',
                }
                for col_name, col_type in ticket_new.items():
                    if col_name not in ticket_cols:
                        conn.execute(text(f'ALTER TABLE tickets ADD COLUMN {col_name} {col_type}'))
                        print(f"Added '{col_name}' column to tickets")
                conn.commit()
            
            # Migration for time_entries table - add new columns
            if 'time_entries' in insp.get_table_names():
                time_cols = [c['name'] for c in insp.get_columns('time_entries')]
                time_new = {
                    'started_at': 'TIMESTAMP WITH TIME ZONE',
                    'ended_at': 'TIMESTAMP WITH TIME ZONE',
                    'is_billable': 'BOOLEAN DEFAULT TRUE',
                    'is_running': 'BOOLEAN DEFAULT FALSE',
                }
                for col_name, col_type in time_new.items():
                    if col_name not in time_cols:
                        conn.execute(text(f'ALTER TABLE time_entries ADD COLUMN {col_name} {col_type}'))
                        print(f"Added '{col_name}' column to time_entries")
                conn.commit()
    except Exception as e:
        print(f"Database initialization error: {e}")
        
    # Start Telegram bot polling as task
    from app.telegram_bot import start_polling
    bot_task = asyncio.create_task(start_polling())
    
    # Start IMAP email polling as task
    from app.services.imap_service import imap_polling_loop
    imap_task = asyncio.create_task(imap_polling_loop())
    
    yield # App runs here
    
    # Shutdown
    bot_task.cancel()
    imap_task.cancel()

# Создание приложения FastAPI
app = FastAPI(
    title=settings.APP_NAME,
    description="Продакшен-готовый бэкенд для системы Service Desk / Help Desk",
    version="2.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
    lifespan=lifespan
)


# Autogenerated migrations now done in lifespan

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.get_allowed_origins(),
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Logging middleware
@app.middleware("http")
async def logging_middleware(request: Request, call_next):
    start_time = time.time()
    response = await call_next(request)
    process_time = time.time() - start_time
    
    log_request(
        method=request.method,
        path=request.url.path,
        status_code=response.status_code,
        duration=process_time
    )
    
    return response

# Подключение роутеров
app.include_router(auth.router, prefix="/api")
app.include_router(tickets.router, prefix="/api")
app.include_router(comments.router, prefix="/api")
app.include_router(notifications.router, prefix="/api")
app.include_router(webhooks.router, prefix="/api")
app.include_router(analytics.router, prefix="/api")
app.include_router(users.router, prefix="/api")
app.include_router(crm.router, prefix="/api")
app.include_router(timetracking.router, prefix="/api")
app.include_router(knowledgebase.router, prefix="/api")
app.include_router(audit.router, prefix="/api")
app.include_router(features.router, prefix="")
app.include_router(reports.router, prefix="/api")


# Эндпоинт проверки здоровья
@app.get("/", tags=["Здоровье"])
def health_check():
    """
    Проверка работоспособности API
    """
    return {
        "статус": "работает",
        "версия": "2.0.0",
        "сообщение": "Service Desk API готов к работе"
    }


# Статистика (для dashboard)
from fastapi import Depends
from sqlalchemy.orm import Session
from app.database import get_db
from app.dependencies import get_current_user
from app.models import Ticket, TicketStatus, User


@app.get("/api/stats", tags=["Статистика"])
def get_stats(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Получить статистику для dashboard
    """
    # Filter by user's tenant
    base_query = db.query(Ticket).filter(Ticket.tenant_id == current_user.tenant_id)
    
    total_tickets = base_query.count()
    
    # Helper to count by status name
    def count_by_status(name):
        return base_query.join(TicketStatus).filter(TicketStatus.name == name).count()
        
    new_tickets = count_by_status("Новый")
    in_progress = count_by_status("В работе")
    resolved = count_by_status("Решён")
    closed = count_by_status("Закрыт")
    
    my_tickets = base_query.filter(Ticket.assigned_to == current_user.id).count()
    my_created = base_query.filter(Ticket.created_by == current_user.id).count()
    
    return {
        "total_tickets": total_tickets,
        "new_tickets": new_tickets,
        "in_progress": in_progress,
        "resolved": resolved,
        "closed": closed,
        "assigned_to_me": my_tickets,
        "created_by_me": my_created
    }

# WebSocket Endpoint
@app.websocket("/ws/{token}")
async def websocket_endpoint(websocket: WebSocket, token: str):
    """
    WebSocket эндпоинт для real-time обновлений
    """
    try:
        # Verify Token
        payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
        user_id_str: str = payload.get("sub")
        tenant_id: int = payload.get("tenant_id")
        
        if user_id_str is None or tenant_id is None:
            await websocket.close(code=1008)
            return
            
        user_id = int(user_id_str)
        
        # Connect
        await manager.connect(websocket, tenant_id, user_id)
        
        try:
            while True:
                # Keep connection alive
                data = await websocket.receive_text()
                # Optional: Handle client-side pings or simple commands
        except WebSocketDisconnect:
            manager.disconnect(websocket, tenant_id, user_id)
            
    except Exception as e:
        print(f"WS Auth Error: {e}")
        await websocket.close(code=1008)
