WS_EVENT_REFRESH = "REFRESH_TICKETS"
WS_EVENT_CREATED = "TICKET_CREATED"
WS_EVENT_RESOLVED = "TICKET_RESOLVED"
WS_EVENT_CLOSED = "TICKET_CLOSED"
WS_EVENT_REOPENED = "TICKET_REOPENED"
WS_EVENT_COMMENT_ADDED = "TICKET_COMMENT_ADDED"
WS_EVENT_NEW_NOTIFICATION = "NEW_NOTIFICATION"

BUSINESS_EVENT_TICKET_CREATED = "ticket_created"
BUSINESS_EVENT_COMMENT_CREATED = "comment_created"

RESOLVED_STATUS_NAME = "Ожидает клиента"
IN_PROGRESS_STATUS_NAME = "В работе"
DEFAULT_ORDER = 1

TIMELINE_EVENT_CREATE = "create"
TIMELINE_EVENT_COMMENT = "comment"
TIMELINE_EVENT_STATUS_CHANGE = "STATUS_CHANGE"
TIMELINE_EVENT_ASSIGNMENT_CHANGE = "ASSIGNMENT_CHANGE"
